# Base Image
FROM node:20-alpine
# Set working directory
WORKDIR /app
# Copy package files and install dependencies
COPY package*.json ./
# install dependencies
RUN npm install
# Copy application code
COPY . .
# Use non-root user
USER node
# Expose application port
EXPOSE 8080
# Start the application
CMD ["node", "server.js"]
